import { Activity, Box, ChevronDown, ChevronRight, Cpu, Database, FileBox, Gauge, HardDrive, Layers3, MemoryStick, MoreHorizontal, PenLine, Pencil, Play, Plus, SlidersHorizontal, Sparkles, Star, Trash2, Zap, type LucideIcon } from "lucide-react";
import { useState } from "react";
import type { AppConfig, ModelAsset, Profile, ServerStatus } from "../types";
import { cn, fileName, formatBytes, modelTitle } from "../utils";
interface Props { config: AppConfig; models: ModelAsset[]; status: ServerStatus; selectedProfiles: Record<string, string>; busy: boolean; onAddModel: () => void; onSelectProfile: (modelId: string, profileId: string) => void; onStart: (model: ModelAsset) => void; onEditProfile: (model: ModelAsset, profile: Profile) => void; onRenameModel: (modelId: string, displayName: string) => void; onSetDefaultModel: (modelId: string) => void; onOpenProfiles: () => void; menuModelId: string | null; onMenuModel: (id: string | null) => void; onRemoveModel: (id: string) => void; }
export default function ModelsPage(props: Props) {
  const totalBytes = props.config.models.reduce((sum, model) => sum + model.sizeBytes, 0);
  const profileCount = props.config.models.reduce((sum, model) => sum + model.profiles.length, 0);
  return <>
    <section className="page-heading"><div><div className="eyebrow"><Sparkles size={14} />MODEL LIBRARY</div><h1>模型仓库</h1><p>管理本地 GGUF 资产，并用不同预设快速启动推理服务。</p></div><div className="page-heading-actions"><button className="primary-button" onClick={props.onAddModel}><Plus size={17} />添加模型</button></div></section>
    <section className="metric-grid"><Metric icon={Database} tone="violet" label="模型资产" value={String(props.config.models.length).padStart(2, "0")} detail="个本地模型" /><Metric icon={HardDrive} tone="cyan" label="磁盘占用" value={formatBytes(totalBytes)} detail="已索引文件" /><Metric icon={SlidersHorizontal} tone="amber" label="运行预设" value={String(profileCount).padStart(2, "0")} detail="组参数方案" /><Metric icon={Zap} tone="green" label="当前状态" value={props.status.running ? "运行中" : "待命"} detail={props.status.running ? `PID ${props.status.pid || "—"}` : "资源占用 0%"} /></section>
    <div className="section-title-row"><div><h2>模型资产</h2><span>{props.models.length} 个结果</span></div><button className="text-button" onClick={props.onOpenProfiles}>管理预设<ChevronRight size={15} /></button></div>
    {props.models.length ? <section className="model-grid">{props.models.map((model) => <ModelCard key={model.id} model={model} profiles={model.profiles} selectedProfileId={props.selectedProfiles[model.id]} defaultProfileId={model.defaultProfileId} isDefaultModel={model.id === props.config.preferredModelId} isRunning={props.status.running && props.status.modelId === model.id} busy={props.busy} menuOpen={props.menuModelId === model.id} onMenu={() => props.onMenuModel(props.menuModelId === model.id ? null : model.id)} onSelectProfile={(profileId) => props.onSelectProfile(model.id, profileId)} onStart={() => props.onStart(model)} onEditProfile={props.onEditProfile} onRenameModel={props.onRenameModel} onSetDefaultModel={props.onSetDefaultModel} onRemove={() => props.onRemoveModel(model.id)} />)}</section> : <div className="empty-state"><div><Box size={28} /></div><h3>没有找到模型</h3><p>点击 添加模型，拖入 GGUF 文件或整个文件夹。</p><div className="empty-actions"><button className="secondary-button" onClick={props.onAddModel}><Plus size={16} />添加模型</button></div></div>}
  </>;
}
function Metric({ icon: Icon, tone, label, value, detail, onClick }: { icon: LucideIcon; tone: string; label: string; value: string; detail: string; onClick?: () => void }) { return <button className="metric-card" onClick={onClick}><div className={cn("metric-icon", tone)}><Icon size={19} /></div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>{onClick && <ChevronRight className="metric-arrow" size={16} />}</button>; }
function ModelCard({ model, profiles, selectedProfileId, defaultProfileId, isDefaultModel, isRunning, busy, menuOpen, onMenu, onSelectProfile, onStart, onEditProfile, onRenameModel, onSetDefaultModel, onRemove }: { model: ModelAsset; profiles: Profile[]; selectedProfileId?: string; defaultProfileId?: string; isDefaultModel: boolean; isRunning: boolean; busy: boolean; menuOpen: boolean; onMenu: () => void; onSelectProfile: (id: string) => void; onStart: () => void; onEditProfile: (model: ModelAsset, profile: Profile) => void; onRenameModel: (modelId: string, displayName: string) => void; onSetDefaultModel: (modelId: string) => void; onRemove: () => void }) {
  const [renaming, setRenaming] = useState(false);
  const [draftName, setDraftName] = useState("");
  const selected = profiles.find((profile) => profile.id === selectedProfileId) || profiles[0];
  const commitRename = () => { onRenameModel(model.id, draftName); setRenaming(false); };
  return <article className={cn("model-card", isRunning && "running")}>
    <div className="model-card-top"><div className={cn("model-symbol", model.accent)}><FileBox size={26} /><span>GGUF</span></div><div className="model-title"><div>{renaming ? <input className="model-rename-input" autoFocus value={draftName} placeholder={modelTitle(model)} onChange={(e) => setDraftName(e.target.value)} onBlur={commitRename} onKeyDown={(e) => { if (e.key === "Enter") commitRename(); if (e.key === "Escape") { setRenaming(false); } }} /> : <h3>{modelTitle(model)}</h3>}{isRunning && <span className="live-badge"><i />LIVE</span>}{isDefaultModel && <span className="default-tag" title="默认启动模型"><Star size={12} fill="currentColor" /></span>}</div><p title={model.path}>{fileName(model.path)}</p></div><div className="model-menu-wrap"><button className="ghost-icon" onClick={onMenu}><MoreHorizontal size={18} /></button>{menuOpen && <div className="context-menu"><button onClick={() => { onSetDefaultModel(model.id); onMenu(); }}><Star size={14} />设为默认</button><button onClick={() => { setDraftName(modelTitle(model)); setRenaming(true); onMenu(); }}><PenLine size={14} />重命名模型</button><button onClick={() => selected && onEditProfile(model, selected)}><Pencil size={14} />编辑当前预设</button><button className="danger" onClick={onRemove}><Trash2 size={14} />移出模型仓库</button></div>}</div></div>
    <div className="model-tags"><span>{model.parameters}</span><span>{model.quantization}</span><span>{model.architecture}</span></div>
    <div className="model-specs"><div><HardDrive size={15} /><span>文件大小</span><strong>{formatBytes(model.sizeBytes)}</strong></div><div><Layers3 size={15} /><span>可用预设</span><strong>{profiles.length} 组</strong></div></div>
    <div className="profile-preview"><div className="profile-preview-head"><span>启动预设</span><button disabled={!selected} onClick={() => selected && onEditProfile(model, selected)}>编辑参数</button></div>{selected ? <div className="profile-pills"><span><MemoryStick size={13} />{selected.gpuLayers} GPU 层</span><span><Gauge size={13} />{(selected.contextSize / 1024).toFixed(0)}K 上下文</span><span><Cpu size={13} />{selected.threads} 线程</span></div> : <p className="no-profile">尚未绑定运行预设</p>}</div>
    <div className="launch-row"><div className="launch-split"><button className={cn("launch-button", isRunning && "active")} disabled={busy || isRunning || !selected} onClick={onStart}>{isRunning ? <><Activity size={15} />正在运行</> : <><Play size={15} fill="currentColor" />启动服务</>}</button><label className="profile-select" title="启动预设"><select value={selected?.id || ""} onChange={(event) => onSelectProfile(event.target.value)} disabled={!profiles.length}>{profiles.map((profile) => <option value={profile.id} key={profile.id}>{profile.name}{profile.id === defaultProfileId ? "（默认）" : ""}</option>)}</select><ChevronDown size={15} /></label></div></div>
  </article>;
}
