import { Save, SlidersHorizontal, X, Zap } from "lucide-react";
import { useState, type ChangeEvent, type ReactNode } from "react";
import type { Profile } from "../types";
import { cn } from "../utils";

const CACHE_TYPES = ["f32", "f16", "q8_0", "q4_0"];
const LOAD_MODES = ["mmap", "mlock", "ragged", "row", "direct"];
const REASONING_MODES = ["auto", "on", "off"];
const REASONING_EFFORTS = ["auto", "low", "medium", "high", "xhigh"];

export default function ProfileEditor({ profile, defaultProfileId, onClose, onSave }: { profile: Profile; defaultProfileId?: string; onClose: () => void; onSave: (profile: Profile, isDefault: boolean) => void }) {
  const [draft, setDraft] = useState(profile);
  const [isDefault, setIsDefault] = useState(profile.id === defaultProfileId);
  const update = <K extends keyof Profile>(key: K, value: Profile[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const number = (key: keyof Profile) => (event: ChangeEvent<HTMLInputElement>) => update(key, Number(event.target.value) as never);
  const select = (key: keyof Profile) => (event: ChangeEvent<HTMLSelectElement>) => update(key, event.target.value as never);
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="profile-editor"><header><div><div className="editor-icon"><SlidersHorizontal size={19} /></div><div><span>RUNTIME PROFILE</span><h2>编辑运行预设</h2></div></div><button className="ghost-icon" onClick={onClose}><X size={19} /></button></header><div className="editor-body">
    <div className="form-section"><div className="form-section-title"><span>01</span><div><h3>预设信息</h3><p>用于识别这组运行参数</p></div></div><div className="form-grid three"><Field label="预设名称"><input value={draft.name} onChange={(e) => update("name", e.target.value)} /></Field><Field label="监听地址" hint="--host"><input value={draft.host} onChange={(e) => update("host", e.target.value)} /></Field><Field label="监听端口" hint="--port"><input type="number" value={draft.port} onChange={number("port")} /></Field><Field label="说明" wide><input value={draft.description} onChange={(e) => update("description", e.target.value)} /></Field><Field label="默认启动配置" wide><button type="button" className={cn("toggle-row", isDefault && "enabled")} onClick={() => setIsDefault((value) => !value)}><span>设为该模型的默认预设</span><i><b /></i></button></Field></div></div>
    <div className="form-section"><div className="form-section-title"><span>02</span><div><h3>性能参数</h3><p>硬件卸载、上下文与批处理规模</p></div></div><div className="form-grid three"><Field label="GPU 层数" hint="-ngl"><input type="number" min="0" value={draft.gpuLayers} onChange={number("gpuLayers")} /></Field><Field label="上下文长度" hint="-c"><input type="number" min="512" step="512" value={draft.contextSize} onChange={number("contextSize")} /></Field><Field label="CPU 线程" hint="-t"><input type="number" min="1" value={draft.threads} onChange={number("threads")} /></Field><Field label="并行槽位" hint="-np"><input type="number" min="1" value={draft.parallel} onChange={number("parallel")} /></Field><Field label="Batch Size" hint="-b"><input type="number" min="32" step="32" value={draft.batchSize} onChange={number("batchSize")} /></Field><Field label="Ubatch Size" hint="-ub"><input type="number" min="32" step="32" value={draft.ubatchSize} onChange={number("ubatchSize")} /></Field></div></div>
    <div className="form-section"><div className="form-section-title"><span>03</span><div><h3>高级选项</h3><p>KV 缓存、注意力与模型加载方式</p></div></div><div className="form-grid three"><Field label="Flash Attention" wide><button type="button" className={cn("toggle-row", draft.flashAttention && "enabled")} onClick={() => update("flashAttention", !draft.flashAttention)}><span><Zap size={15} />启用 Flash Attention（-fa on）</span><i><b /></i></button></Field><Field label="KV 缓存类型 K" hint="--cache-type-k"><select value={draft.cacheTypeK} onChange={select("cacheTypeK")}>{CACHE_TYPES.map((value) => <option key={value} value={value}>{value}</option>)}</select></Field><Field label="KV 缓存类型 V" hint="--cache-type-v"><select value={draft.cacheTypeV} onChange={select("cacheTypeV")}>{CACHE_TYPES.map((value) => <option key={value} value={value}>{value}</option>)}</select></Field><Field label="加载模式" hint="--load-mode"><select value={draft.loadMode} onChange={select("loadMode")}>{LOAD_MODES.map((value) => <option key={value} value={value}>{value}</option>)}</select></Field><Field label="Jinja 模板" wide><button type="button" className={cn("toggle-row", draft.jinja && "enabled")} onClick={() => update("jinja", !draft.jinja)}><span>启用 Jinja 完整模板（--jinja）</span><i><b /></i></button></Field></div></div>
    <div className="form-section"><div className="form-section-title"><span>04</span><div><h3>推理设置</h3><p>Reasoning 输出开关与思考强度</p></div></div><div className="form-grid two"><Field label="推理模式" hint="--reasoning"><select value={draft.reasoning} onChange={select("reasoning")}>{REASONING_MODES.map((value) => <option key={value} value={value}>{value}</option>)}</select></Field><Field label="推理强度" hint="--reasoning-effort"><select value={draft.reasoningEffort} onChange={select("reasoningEffort")}>{REASONING_EFFORTS.map((value) => <option key={value} value={value}>{value}</option>)}</select></Field></div></div>
    <div className="form-section"><div className="form-section-title"><span>05</span><div><h3>采样控制</h3><p>模型输出的随机性与重复约束</p></div></div><div className="form-grid four"><Field label="Temperature"><input type="number" min="0" max="2" step="0.05" value={draft.temperature} onChange={number("temperature")} /></Field><Field label="Top-P"><input type="number" min="0" max="1" step="0.01" value={draft.topP} onChange={number("topP")} /></Field><Field label="Min-P"><input type="number" min="0" max="1" step="0.01" value={draft.minP} onChange={number("minP")} /></Field><Field label="Repeat Penalty"><input type="number" min="0" step="0.01" value={draft.repeatPenalty} onChange={number("repeatPenalty")} /></Field></div></div>
    <div className="form-section"><div className="form-section-title"><span>06</span><div><h3>自定义注入</h3><p>原样追加到 llama-server 命令行</p></div></div><Field label="Extra Arguments" hint="实验性"><textarea value={draft.extraArgs} onChange={(e) => update("extraArgs", e.target.value)} placeholder="--no-warmup --cont-batching" /></Field></div>
  </div><footer><button className="secondary-button" onClick={onClose}>取消</button><button className="primary-button" onClick={() => onSave(draft, isDefault)}><Save size={16} />保存预设</button></footer></section></div>;
}
function Field({ label, hint, wide, children }: { label: string; hint?: string; wide?: boolean; children: ReactNode }) { return <label className={cn("field", wide && "wide")}><span>{label}{hint && <em>{hint}</em>}</span>{children}</label>; }
