import { Copy, MoreHorizontal, Pencil, Plus, Star, Trash2 } from "lucide-react";
import { useState } from "react";
import { DEFAULT_PROFILES, uid } from "../data";
import type { ModelAsset, Profile } from "../types";
import { ACCENTS, cn } from "../utils";

export default function ProfilesPage({ models, onEdit, onDelete, onDuplicate, onSetDefault }: { models: ModelAsset[]; onEdit: (modelId: string, profile: Profile) => void; onDelete: (modelId: string, profileId: string) => void; onDuplicate: (modelId: string, profile: Profile) => void; onSetDefault: (modelId: string, profileId: string) => void }) {
  const [selectedModelId, setSelectedModelId] = useState<string>(models[0]?.id || "");
  const [menuProfileId, setMenuProfileId] = useState<string | null>(null);
  const model = models.find((item) => item.id === selectedModelId) || models[0];
  const profiles = model?.profiles || [];
  const create = () => { if (model) onEdit(model.id, { ...DEFAULT_PROFILES[0], id: uid("profile"), name: "新运行预设", description: "自定义 llama.cpp 启动参数" }); };
  return <>
  <div className="profile-model-bar"><label>当前模型</label><select value={model?.id || ""} onChange={(event) => { setMenuProfileId(null); setSelectedModelId(event.target.value); }} disabled={!models.length}>{models.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="primary-button" onClick={create} disabled={!model}><Plus size={17} />新建预设</button></div>
  {profiles.length ? <section className="profiles-grid">{profiles.map((profile, index) => { const isDefault = model?.defaultProfileId === profile.id; return <article className={cn("profile-card", isDefault && "default")} key={profile.id}>{isDefault && <span className="corner-flag"><Star size={11} fill="currentColor" /></span>}<div className={cn("profile-number", ACCENTS[index % ACCENTS.length])}>0{index + 1}</div><div className="profile-card-head"><div><h3>{profile.name}</h3><p>{profile.description}</p></div><div className="model-menu-wrap"><button className="ghost-icon" onClick={() => setMenuProfileId(menuProfileId === profile.id ? null : profile.id)}><MoreHorizontal size={18} /></button>{menuProfileId === profile.id && <div className="context-menu"><button onClick={() => { if (model) onSetDefault(model.id, profile.id); setMenuProfileId(null); }}><Star size={14} />{isDefault ? "取消默认" : "设为默认"}</button><button className="danger" onClick={() => { if (model) onDelete(model.id, profile.id); setMenuProfileId(null); }}><Trash2 size={14} />删除预设</button></div>}</div></div><div className="profile-stat-grid"><div><span>GPU 卸载</span><strong>{profile.gpuLayers} 层</strong></div><div><span>上下文</span><strong>{profile.contextSize.toLocaleString()}</strong></div><div><span>批大小 -b / -ub</span><strong>{profile.batchSize} / {profile.ubatchSize}</strong></div><div><span>监听地址</span><strong>{profile.host}:{profile.port}</strong></div></div><div className="profile-flags"><span className={profile.flashAttention ? "enabled" : ""}>Flash Attention</span>{profile.jinja && <span className="enabled">Jinja</span>}{profile.cacheTypeK !== "f32" && <span>Cache {profile.cacheTypeK}</span>}{profile.reasoning === "on" && profile.reasoningEffort !== "auto" && <span className="enabled">{profile.reasoningEffort}</span>}</div><div className="profile-card-actions"><button className="secondary-button" onClick={() => model && onEdit(model.id, profile)}><Pencil size={14} />编辑预设</button><button className="secondary-button" onClick={() => model && onDuplicate(model.id, profile)}><Copy size={14} />复制</button></div></article>; })}</section> : <div className="empty-state"><div><Plus size={26} /></div><h3>该模型还没有预设</h3><p>为「{model?.name || "当前模型"}」新建一个运行预设。</p><button className="secondary-button" onClick={create}><Plus size={16} />新建预设</button></div>}
  </>;
}