import { Activity, Check, Database, FolderOpen, Moon, Save, Server, SquareTerminal, Sun } from "lucide-react";
import { useState } from "react";
import { pickFiles } from "../tauri";
import type { AppConfig, LlamaLogPayload } from "../types";

export default function SettingsPage({ config, onPersist, onLog }: { config: AppConfig; onPersist: (config: AppConfig, message?: string) => Promise<void>; onLog: (line: string, stream?: LlamaLogPayload["stream"]) => void }) {
  const [serverPath, setServerPath] = useState(config.serverPath);
  const choose = async () => { const picked = (await pickFiles(["exe"]))[0]; if (picked) setServerPath(picked.path); };
  return <><section className="settings-stack"><div className="settings-card"><div className="settings-card-icon"><Server size={21} /></div><div className="settings-card-body"><h3>llama-server 可执行文件</h3><p>选择本机 llama.cpp 构建目录中的 llama-server.exe。</p><div className="path-field"><input value={serverPath} onChange={(e) => setServerPath(e.target.value)} placeholder="C:\\llama.cpp\\llama-server.exe" /><button onClick={() => void choose()}><FolderOpen size={16} />浏览</button></div></div></div><div className="settings-card"><div className="settings-card-icon cyan"><Database size={21} /></div><div className="settings-card-body"><h3>配置存储</h3><p>Tauri 桌面端会将模型索引与运行预设保存至应用配置目录，不上传任何数据。</p><div className="storage-note"><Check size={15} />Local only · JSON storage · Atomic write</div></div></div><div className="settings-card"><div className="settings-card-icon amber"><Sun size={21} /></div><div className="settings-card-body"><h3>外观主题</h3><p>切换暗色 / 亮色主题，立即生效并持久化。</p><div className="theme-toggle"><button className={config.theme !== "light" ? "active" : ""} onClick={() => void onPersist({ ...config, theme: "dark" }, "已切换暗色主题")}><Moon size={15} />暗色</button><button className={config.theme === "light" ? "active" : ""} onClick={() => void onPersist({ ...config, theme: "light" }, "已切换亮色主题")}><Sun size={15} />亮色</button></div></div></div><div className="settings-card"><div className="settings-card-icon amber"><SquareTerminal size={21} /></div><div className="settings-card-body"><h3>诊断</h3><p>向控制台写入测试消息，检查前端事件与日志抽屉是否正常。</p><button className="secondary-button compact" onClick={() => onLog("diagnostics: UI event bridge is working", "system")}><Activity size={15} />发送测试日志</button></div></div><div className="settings-actions"><button className="primary-button" onClick={() => void onPersist({ ...config, serverPath }, "设置已保存")}><Save size={16} />保存设置</button></div></section></>;
}
